In [1]:
import pandas as pd
import os
import numpy as np
# Load the data
data_path = os.path.join(os.getcwd(), "data", "proid_unique_20231017.dta")
proid_unique = pd.read_stata(data_path)

# Check the data
print(proid_unique.head())
print(proid_unique.dtypes)

       proid       country1  emaskcd  amaskcd
0  561218862  United States      332   113165
1     410881  United States     7139   106982
2   60741673  United States     7139   110604
3   60741837  United States     7139   124930
4   60890589  United States     7139   118924
proid        int32
country1    object
emaskcd      int32
amaskcd      int32
dtype: object

In [2]:
# load the id2firms_all.txt file to dataframe
id2firm_path = os.path.join(os.getcwd(), "data", "input", "id2firms_all.txt")
id2firms = pd.read_csv(id2firm_path, sep='\t', header=0)

In [3]:
print(id2firms.dtypes)
id2firms.head(100)

transcriptid                   float64
companyid                        int64
gvkey                          float64
year                           float64
quarter                          int64
date                            object
transcriptcomponenttypename     object
sentenceid                     float64
componentorder                 float64
proid                          float64
transcriptpersonname            object
word_count                     float64
dtype: object

,transcriptid,companyid,gvkey,year,quarter,date,transcriptcomponenttypename,sentenceid,componentorder,proid,transcriptpersonname,word_count
0,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559554.0,0.0,422945.0,Michael Queen,193.0
1,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559555.0,1.0,25320169.0,Julia Wilson,1274.0
2,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559556.0,2.0,2011654.0,Cressida Hogg,1147.0
3,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559557.0,3.0,422945.0,Michael Queen,2253.0
4,94097.0,18511,210835.0,2010.0,4,2010-11-11,Question,6559558.0,4.0,98902521.0,Christopher Brown,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,309239.0,18511,210835.0,2012.0,2,2012-05-17,Question,15129004.0,7.0,27460816.0,Philip Middleton,61.0
96,309043.0,18511,210835.0,2012.0,2,2012-05-17,Answer,15122823.0,8.0,137078002.0,Simon Borrows,1.0
97,309239.0,18511,210835.0,2012.0,2,2012-05-17,Answer,15129006.0,9.0,106826319.0,Adrian Montague,1.0
98,309043.0,18511,210835.0,2012.0,2,2012-05-17,Question,15122824.0,9.0,106840755.0,Daniel Garrod,114.0
99,309043.0,18511,210835.0,2012.0,2,2012-05-17,Answer,15122825.0,10.0,25320169.0,Julia Wilson,314.0

In [4]:
# convert the proid column to int
id2firms['proid'].fillna(-999, inplace=True)
id2firms['proid'] = id2firms['proid'].astype(int)
id2firms = pd.merge(id2firms, proid_unique, on='proid', how='left')

In [5]:
id2firms.head()

,transcriptid,companyid,gvkey,year,quarter,date,transcriptcomponenttypename,sentenceid,componentorder,proid,transcriptpersonname,word_count,country1,emaskcd,amaskcd
0,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559554.0,0.0,422945,Michael Queen,193.0,NaN,NaN,NaN
1,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559555.0,1.0,25320169,Julia Wilson,1274.0,NaN,NaN,NaN
2,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559556.0,2.0,2011654,Cressida Hogg,1147.0,NaN,NaN,NaN
3,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559557.0,3.0,422945,Michael Queen,2253.0,NaN,NaN,NaN
4,94097.0,18511,210835.0,2010.0,4,2010-11-11,Question,6559558.0,4.0,98902521,Christopher Brown,46.0,United Kingdom,1243.0,106321.0

In [6]:
# load the Allstar analysts data
all_star_path = os.path.join(os.getcwd(), "data", "Allstar.dta")
all_star = pd.read_stata(all_star_path)

In [7]:
# merge the all_star data with the id2firms data
all_star.columns = ['year', 'emaskcd', 'amaskcd']
all_star['all_star'] = 1
id2firms = pd.merge(id2firms, all_star, on=['year', 'emaskcd', 'amaskcd'], how='left')
id2firms.head()

,transcriptid,companyid,gvkey,year,quarter,date,transcriptcomponenttypename,sentenceid,componentorder,proid,transcriptpersonname,word_count,country1,emaskcd,amaskcd,all_star
0,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559554.0,0.0,422945,Michael Queen,193.0,NaN,NaN,NaN,NaN
1,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559555.0,1.0,25320169,Julia Wilson,1274.0,NaN,NaN,NaN,NaN
2,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559556.0,2.0,2011654,Cressida Hogg,1147.0,NaN,NaN,NaN,NaN
3,94097.0,18511,210835.0,2010.0,4,2010-11-11,Presenter Speech,6559557.0,3.0,422945,Michael Queen,2253.0,NaN,NaN,NaN,NaN
4,94097.0,18511,210835.0,2010.0,4,2010-11-11,Question,6559558.0,4.0,98902521,Christopher Brown,46.0,United Kingdom,1243.0,106321.0,NaN

In [8]:
analyst_exp_path = os.path.join(os.getcwd(), "data", "analyst_experience_fyear_20220611.dta")
analyst_exp = pd.read_stata(analyst_exp_path)

In [9]:
analyst_exp.head()

   gvkey   fyear  AMASKCD  EMASKCD  GenExp  FirmExp  Broker_size
0   1004  1999.0    705.0     1997    19.0      4.0          8.0
1   1004  2000.0    705.0     1997    19.0      4.0         21.0
2   1004  2016.0    965.0     7019    35.0      1.0          7.0
3   1004  2017.0    965.0     7019    35.0      1.0          8.0
4   1004  1999.0   1098.0      295    15.0      4.0         19.0

In [10]:
# merge the analyst_exp data with the id2firms data on gvkey, year, amaskcd and emaskcd
analyst_exp.rename(columns={'fyear': 'year', 'AMASKCD': 'amaskcd', 'EMASKCD': 'emaskcd'}, inplace=True)
id2firms = pd.merge(id2firms, analyst_exp, on=['gvkey', 'year', 'amaskcd', 'emaskcd'], how='left')

:

In [ ]:
id2firms

In [ ]:
# write a code to compute the Topic Attention Divergence for each firm in id2firms (TAD)
# design the optimal algorithm to compute the 
# write a function to load the narratives data by sentence_id, 
# filepath = /outputs/scores/TF/combined_scores_TF.csv narratives_path = os.path.join(os.getcwd(), "w2v_culture", "outputs", "scores", "TF", "combined_scores_TF.csv")
# load the narratives data in the function in chunks of 100000 rows
# write a function to compute the TAD for each firm in id2firms
# the function should take the narratives data and the firm_id as input
# the function should return the TAD for the firm

# standardize the narratives data by divide the score based on the 
from tqdm import tqdm

class TAD:
    def __init__(self, model = 'TFIDF'):
        self.narratives_path = os.path.join(os.getcwd(), "w2v_culture", "outputs", "scores", f"{model}", f"combined_scores_{model}.csv")
        self.word_contribution_path = os.path.join(os.getcwd(), "w2v_culture", "outputs", "scores", "word_contribution")
        self.narratives = self.load_narratives()
        self.word_contributions, self.word_contribution_len = self.read_word_contribution()
        self.model_type = model
        self.topics_ = self.word_contribution.keys()

    def load_narratives(self):
        # load the narratives data in the function in chunks of 100000 rows
        narratives = pd.read_csv(self.narratives_path, chunksize=100000)
        return narratives

    def merge_narratives_with_id2firms(self, id2firms):
        # merge the narratives data with the id2firms data
        id2firms = pd.merge(id2firms, self.narratives, on='sentence_id', how='left')
        # standardize the narratives data by divide the score based on the 
        return id2firms
    
    def read_word_contribution(self):
        # Read all CSV files from the word contributions directory to a dictionary
        # input: the word contribution path, with a topic folder for each topic csv file
        # output: a dictionary with the topic as the key and the dataframe as the value, 
        # output2: a list with the topic as key and list of length of each topic
        word_contributions = {}
        word_contribution_len = []
        for topic in os.listdir(self.word_contribution_path):
            topic_path = os.path.join(self.word_contribution_path, topic)
            if os.path.isdir(topic_path):  # Check if it's a directory
                for file in os.listdir(topic_path):
                    if file.endswith('.csv') and f'{self.model_type}' in file:
                        file_path = os.path.join(topic_path, file)
                        df = pd.read_csv(file_path)
                        df.columns = ['words', 'words_weight']
                        word_contributions[topic] = df
                        word_contribution_len.append(len(df))
            else:
                print(f"Skipping non-directory item: {topic_path}")
        return word_contributions, word_contribution_len
    

    def compute_cosine_similarity(self, v1, v2):
        # compute the cosine similarity between two vectors
        # input: two vectors
        # output: the cosine similarity
        return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
    
    def get_v_a_con(self, row_doc, section_id = 'Ptranscriptcomponenttypename'):
        # get the vector for each firm_id, year, quarter (conference call level)
        # input: the row_doc each row is a conference call, firm_id, year, quarter 
        temp_doc = row_doc.groupby([section_id])[self.topics_].mean().reset_index()

        # convert the temp_doc to a list of vectors, vector of presenterspeech, question, answer
        vps = temp_doc[temp_doc['transcriptcomponenttypename'] == 'Presenter Speech']
        vq = temp_doc[temp_doc['transcriptcomponenttypename'] == 'Question']
        va = temp_doc[temp_doc['transcriptcomponenttypename'] == 'Answer']
        # get the vector for each firm_id, year, quarter for Presenter Speech
        ps_vector = vps[self.topics_].values
        q_vector = vq[self.topics_].values
        a_vector = va[self.topics_].values
        # get the consine_similarity for each document
        tad_ps_q = 1 - self.compute_cosine_similarity(ps_vector, q_vector)
        tad_ps_a = 1 - self.compute_cosine_similarity(ps_vector, a_vector)
        tad_q_a = 1 - self.compute_cosine_similarity(q_vector, a_vector)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    o
        return tad_ps_q, tad_ps_a, tad_q_a

    def cpt_firm_TAD(self, df, firm_id = 'gvkey'):
        # compute the cosine similarity between the word contribution and the narratives
        # input: the id2firms data
        # keys: the keys to group the data by firm_id, year and quarter, and section_id 
        # output: the cosine similarity for each firm
        # Get word contributions and their lengths
        wcd = self.word_contributions
        keys = [f'{firm_id}', 'year', 'quarter']
        grouped = df.groupby(keys)
        result = []
        # process each document
        for names, group in tqdm(grouped, desc="Computing Cosine Similarity", bar_format='{l_bar}{bar:10}{r_bar}{bar:-10b}', colour="green"):
            doc_vector = {}
            # get the vector for each firm_id, and year quarter for Presenter Speech
            # Create document vector for each 
            tad_ps_q, tad_ps_a, tad_q_a = self.get_v_a_con(group)
            # save the TAD score for each firm, year, quarter
            result.append({'gvkey': names[0], 'year': names[1], 'quarter': names[2], 'tad_ps_q': tad_ps_q, 'tad_ps_a': tad_ps_a, 'tad_q_a': tad_q_a})
        return result
    
    def compute_TAD(self, id2firms):
        # standardize the topic attention in id2firms
        # input: the id2firms data
        # output: the TAD for each firm
        wcd, wcl = self.read_word_contribution() # read the word contribution dictionary and the word contribution length
        # compute the TAD for each firm
        for topic in tqdm(wcd.keys(), desc="Computing TAD", bar_format='{l_bar}{bar:10}{r_bar}{bar:-10b}', colour="green"):
            # standardize the topic attention in id2firms
            id2firms[topic] = id2firms.apply(lambda x: x[topic] / (wcl[topic] * x['document_length']), axis=1)
        # aggregate the TAD from sentence level to section level
            # compute the TAD for each firm
        return id2firms 
    
    
    

    

for index, row in id2firms.iterrows():
    firm_id = row['gvkey']
    year = row['year']
    # get the narratives data

In [3]:
# load the narratives data by sentence_id, /outputs/scores/TF/combined_scores_TF.csv
narratives_path = os.path.join(os.getcwd(), "w2v_culture", "outputs", "scores", "TF", "combined_scores_TF.csv")
narratives = pd.read_csv(narratives_path)
narratives.head()

: